server:
  port: 8080

spring:
  application:
    name: llm-assistant-backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # ğŸŸ¢ å•ä¸ªæ–‡ä»¶æœ€å¤§é™åˆ¶ (æ¯”å¦‚æ”¹æˆ 50MB)
      max-request-size: 100MB  # ğŸŸ¢ ä¸€æ¬¡è¯·æ±‚æ‰€æœ‰æ–‡ä»¶çš„æ€»å¤§å°é™åˆ¶ (æ¯”å¦‚æ”¹æˆ 100MB)

  datasource:
    url: jdbc:mysql://localhost:3306/llm_assistant?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver


  ai:
    zhipuai:
      api-key: ${SPRING_AI_ZHIPUAI_API_KEY:} # ???????????? API Key
      chat:
        options:
          model: glm-4-flash
          temperature: 0.7


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # ??????? user_name ?? Java ? userName
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????? SQL?????